package bc3s;

import static java.lang.Integer.parseInt;

/**
 *
 * @author Forrest Swift
 */
public class BC3SGUI extends javax.swing.JFrame {
    /**
     * Creates new form BC3SGUI
     */
    public BC3SGUI() {
        initComponents();
        StringBuilder str = new StringBuilder();
        str.append("To use this program:\n\n");
        str.append("Enter in the starting Sudoku values.\n\n");
        str.append("Hit submit to run the Sudoku solver.\n\n");
        str.append("Hit clear to wipe the board for another round.");
        HelpPanel.setText(str.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        sudoTitle = new javax.swing.JTextField();
        board15 = new javax.swing.JTextField();
        board16 = new javax.swing.JTextField();
        board17 = new javax.swing.JTextField();
        board18 = new javax.swing.JTextField();
        board19 = new javax.swing.JTextField();
        board11 = new javax.swing.JTextField();
        board12 = new javax.swing.JTextField();
        board13 = new javax.swing.JTextField();
        board14 = new javax.swing.JTextField();
        board25 = new javax.swing.JTextField();
        board26 = new javax.swing.JTextField();
        board27 = new javax.swing.JTextField();
        board28 = new javax.swing.JTextField();
        board29 = new javax.swing.JTextField();
        board21 = new javax.swing.JTextField();
        board22 = new javax.swing.JTextField();
        board23 = new javax.swing.JTextField();
        board24 = new javax.swing.JTextField();
        board35 = new javax.swing.JTextField();
        board36 = new javax.swing.JTextField();
        board37 = new javax.swing.JTextField();
        board38 = new javax.swing.JTextField();
        board39 = new javax.swing.JTextField();
        board31 = new javax.swing.JTextField();
        board32 = new javax.swing.JTextField();
        board33 = new javax.swing.JTextField();
        board34 = new javax.swing.JTextField();
        board45 = new javax.swing.JTextField();
        board46 = new javax.swing.JTextField();
        board47 = new javax.swing.JTextField();
        board48 = new javax.swing.JTextField();
        board49 = new javax.swing.JTextField();
        board41 = new javax.swing.JTextField();
        board42 = new javax.swing.JTextField();
        board43 = new javax.swing.JTextField();
        board44 = new javax.swing.JTextField();
        board55 = new javax.swing.JTextField();
        board56 = new javax.swing.JTextField();
        board57 = new javax.swing.JTextField();
        board58 = new javax.swing.JTextField();
        board59 = new javax.swing.JTextField();
        board51 = new javax.swing.JTextField();
        board52 = new javax.swing.JTextField();
        board53 = new javax.swing.JTextField();
        board54 = new javax.swing.JTextField();
        board65 = new javax.swing.JTextField();
        board66 = new javax.swing.JTextField();
        board67 = new javax.swing.JTextField();
        board68 = new javax.swing.JTextField();
        board69 = new javax.swing.JTextField();
        board61 = new javax.swing.JTextField();
        board62 = new javax.swing.JTextField();
        board63 = new javax.swing.JTextField();
        board64 = new javax.swing.JTextField();
        board75 = new javax.swing.JTextField();
        board76 = new javax.swing.JTextField();
        board77 = new javax.swing.JTextField();
        board78 = new javax.swing.JTextField();
        board79 = new javax.swing.JTextField();
        board71 = new javax.swing.JTextField();
        board72 = new javax.swing.JTextField();
        board73 = new javax.swing.JTextField();
        board74 = new javax.swing.JTextField();
        board85 = new javax.swing.JTextField();
        board86 = new javax.swing.JTextField();
        board87 = new javax.swing.JTextField();
        board88 = new javax.swing.JTextField();
        board89 = new javax.swing.JTextField();
        board81 = new javax.swing.JTextField();
        board82 = new javax.swing.JTextField();
        board83 = new javax.swing.JTextField();
        board84 = new javax.swing.JTextField();
        board95 = new javax.swing.JTextField();
        board96 = new javax.swing.JTextField();
        board97 = new javax.swing.JTextField();
        board98 = new javax.swing.JTextField();
        board99 = new javax.swing.JTextField();
        board91 = new javax.swing.JTextField();
        board92 = new javax.swing.JTextField();
        board93 = new javax.swing.JTextField();
        board94 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 500), new java.awt.Dimension(0, 500), new java.awt.Dimension(32767, 500));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 500), new java.awt.Dimension(0, 500), new java.awt.Dimension(32767, 500));
        SubmitButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HelpPanel = new javax.swing.JTextPane();

        jTextField10.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        sudoTitle.setEditable(false);
        sudoTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sudoTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sudoTitle.setText("Backtracking Constraint Satisfaction Sudoku Solver");
        sudoTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudoTitleActionPerformed(evt);
            }
        });

        board15.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board16.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board17.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board19.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board19.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board11.setText("8");

        board12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board25.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board26.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board27.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board28.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board29.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board21.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board22.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board23.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board23.setText("3");

        board24.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board24.setText("6");

        board35.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board35.setText("9");

        board36.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board37.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board37.setText("2");

        board38.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board38.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board39.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board39.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board31.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board32.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board32.setText("7");

        board33.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board34.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board45.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board45.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board46.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board46.setText("7");

        board47.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board47.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board48.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board48.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board49.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board49.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board41.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board41.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board42.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board42.setText("5");

        board43.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board43.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board44.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board55.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board55.setText("4");

        board56.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board56.setText("5");

        board57.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board57.setText("7");

        board58.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board58.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board59.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board59.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board51.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board51.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board52.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board52.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board53.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board53.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board54.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board54.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board65.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board65.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board66.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board67.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board67.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board68.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board68.setText("3");

        board69.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board69.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board61.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board61.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board62.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board62.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board63.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board63.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board64.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board64.setText("1");

        board75.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board75.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board76.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board76.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board77.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board77.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board78.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board78.setText("6");

        board79.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board79.setText("8");

        board71.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board71.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board72.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board72.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board73.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board73.setText("1");

        board74.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board74.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board85.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board85.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board86.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board86.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board87.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board87.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board88.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board88.setText("1");

        board89.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board89.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board81.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board81.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board82.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board82.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board83.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board83.setText("8");

        board84.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board84.setText("5");

        board95.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board95.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board96.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board96.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board97.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board97.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board97.setText("4");

        board98.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board98.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board99.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board99.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board91.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board91.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board92.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board92.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        board92.setText("9");

        board93.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board93.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        board94.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        board94.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(HelpPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(board51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(board41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(board21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(board11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(board31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(board61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(board91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(board93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(board87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(board77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(board79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sudoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(ClearButton)
                    .addComponent(sudoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(board11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(board21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(board34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(board35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(board31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(board39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(board41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(board49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(board51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(board61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(board71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(board81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(board91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(board99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sudoTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudoTitleActionPerformed
        
    }//GEN-LAST:event_sudoTitleActionPerformed

    /**
     * Empties all cells in the BC3SGUI.
     * @param evt 
     */
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        board11.setText("");
        board11.setText("");
        board12.setText("");
        board13.setText("");
        board14.setText("");
        board15.setText("");
        board16.setText("");
        board17.setText("");
        board18.setText("");
        board19.setText("");
        board21.setText("");
        board22.setText("");
        board23.setText("");
        board24.setText("");
        board25.setText("");
        board26.setText("");
        board27.setText("");
        board28.setText("");
        board29.setText("");
        board31.setText("");
        board32.setText("");
        board33.setText("");
        board34.setText("");
        board35.setText("");
        board36.setText("");
        board37.setText("");
        board38.setText("");
        board39.setText("");
        board41.setText("");
        board42.setText("");
        board43.setText("");
        board44.setText("");
        board45.setText("");
        board46.setText("");
        board47.setText("");
        board48.setText("");
        board49.setText("");
        board51.setText("");
        board52.setText("");
        board53.setText("");
        board54.setText("");
        board55.setText("");
        board56.setText("");
        board57.setText("");
        board58.setText("");
        board59.setText("");
        board61.setText("");
        board62.setText("");
        board63.setText("");
        board64.setText("");
        board65.setText("");
        board66.setText("");
        board67.setText("");
        board68.setText("");
        board69.setText("");
        board71.setText("");
        board72.setText("");
        board73.setText("");
        board74.setText("");
        board75.setText("");
        board76.setText("");
        board77.setText("");
        board78.setText("");
        board79.setText("");
        board81.setText("");
        board82.setText("");
        board83.setText("");
        board84.setText("");
        board85.setText("");
        board86.setText("");
        board87.setText("");
        board88.setText("");
        board89.setText("");
        board91.setText("");
        board92.setText("");
        board93.setText("");
        board94.setText("");
        board95.setText("");
        board96.setText("");
        board97.setText("");
        board98.setText("");
        board99.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * Submits a sudoku grid to the BC3S solver.
     * Creates a new BC3S instance, sets up the grid, calls the solver, and
     * displays the grid on the GUI.
     * @param evt 
     */
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        BC3S s = new BC3S();
        setupGrid(s);
        s.calcConstraints();
        s.solver();
        displayGrid(s);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * Copies a grid from BC3S into a displayable format for the GUI.
     * I did this all with find/replace. There had to have been a better way.
     * @param s A BC3S solver.
     */
    private void displayGrid(BC3S s) {
        board11.setText("" + s.grid[0][0].value);
        board12.setText("" + s.grid[0][1].value);
        board13.setText("" + s.grid[0][2].value);
        board14.setText("" + s.grid[0][3].value);
        board15.setText("" + s.grid[0][4].value);
        board16.setText("" + s.grid[0][5].value);
        board17.setText("" + s.grid[0][6].value);
        board18.setText("" + s.grid[0][7].value);
        board19.setText("" + s.grid[0][8].value);
        board21.setText("" + s.grid[1][0].value);
        board22.setText("" + s.grid[1][1].value);
        board23.setText("" + s.grid[1][2].value);
        board24.setText("" + s.grid[1][3].value);
        board25.setText("" + s.grid[1][4].value);
        board26.setText("" + s.grid[1][5].value);
        board27.setText("" + s.grid[1][6].value);
        board28.setText("" + s.grid[1][7].value);
        board29.setText("" + s.grid[1][8].value);
        board31.setText("" + s.grid[2][0].value);
        board32.setText("" + s.grid[2][1].value);
        board33.setText("" + s.grid[2][2].value);
        board34.setText("" + s.grid[2][3].value);
        board35.setText("" + s.grid[2][4].value);
        board36.setText("" + s.grid[2][5].value);
        board37.setText("" + s.grid[2][6].value);
        board38.setText("" + s.grid[2][7].value);
        board39.setText("" + s.grid[2][8].value);
        board41.setText("" + s.grid[3][0].value);
        board42.setText("" + s.grid[3][1].value);
        board43.setText("" + s.grid[3][2].value);
        board44.setText("" + s.grid[3][3].value);
        board45.setText("" + s.grid[3][4].value);
        board46.setText("" + s.grid[3][5].value);
        board47.setText("" + s.grid[3][6].value);
        board48.setText("" + s.grid[3][7].value);
        board49.setText("" + s.grid[3][8].value);
        board51.setText("" + s.grid[4][0].value);
        board52.setText("" + s.grid[4][1].value);
        board53.setText("" + s.grid[4][2].value);
        board54.setText("" + s.grid[4][3].value);
        board55.setText("" + s.grid[4][4].value);
        board56.setText("" + s.grid[4][5].value);
        board57.setText("" + s.grid[4][6].value);
        board58.setText("" + s.grid[4][7].value);
        board59.setText("" + s.grid[4][8].value);
        board61.setText("" + s.grid[5][0].value);
        board62.setText("" + s.grid[5][1].value);
        board63.setText("" + s.grid[5][2].value);
        board64.setText("" + s.grid[5][3].value);
        board65.setText("" + s.grid[5][4].value);
        board66.setText("" + s.grid[5][5].value);
        board67.setText("" + s.grid[5][6].value);
        board68.setText("" + s.grid[5][7].value);
        board69.setText("" + s.grid[5][8].value);
        board71.setText("" + s.grid[6][0].value);
        board72.setText("" + s.grid[6][1].value);
        board73.setText("" + s.grid[6][2].value);
        board74.setText("" + s.grid[6][3].value);
        board75.setText("" + s.grid[6][4].value);
        board76.setText("" + s.grid[6][5].value);
        board77.setText("" + s.grid[6][6].value);
        board78.setText("" + s.grid[6][7].value);
        board79.setText("" + s.grid[6][8].value);
        board81.setText("" + s.grid[7][0].value);
        board82.setText("" + s.grid[7][1].value);
        board83.setText("" + s.grid[7][2].value);
        board84.setText("" + s.grid[7][3].value);
        board85.setText("" + s.grid[7][4].value);
        board86.setText("" + s.grid[7][5].value);
        board87.setText("" + s.grid[7][6].value);
        board88.setText("" + s.grid[7][7].value);
        board89.setText("" + s.grid[7][8].value);
        board91.setText("" + s.grid[8][0].value);
        board92.setText("" + s.grid[8][1].value);
        board93.setText("" + s.grid[8][2].value);
        board94.setText("" + s.grid[8][3].value);
        board95.setText("" + s.grid[8][4].value);
        board96.setText("" + s.grid[8][5].value);
        board97.setText("" + s.grid[8][6].value);
        board98.setText("" + s.grid[8][7].value);
        board99.setText("" + s.grid[8][8].value);
    }
    
    /**
     * Copies a grid from the BC3SGUI into a BC3S format for the solver.
     * I did this all with find/replace. There had to have been a better way.
     * @param s A BC3S solver.
     */
    private void setupGrid(BC3S s){
        if (board11.getText().length() > 0) {
            s.grid[0][0].value = parseInt(board11.getText());
        }
        if (board12.getText().length() > 0) {
            s.grid[0][1].value = parseInt(board12.getText());
        }
        if (board13.getText().length() > 0) {
            s.grid[0][2].value = parseInt(board13.getText());
        }
        if (board14.getText().length() > 0) {
            s.grid[0][3].value = parseInt(board14.getText());
        }
        if (board15.getText().length() > 0) {
            s.grid[0][4].value = parseInt(board15.getText());
        }
        if (board16.getText().length() > 0) {
            s.grid[0][5].value = parseInt(board16.getText());
        }
        if (board17.getText().length() > 0) {
            s.grid[0][6].value = parseInt(board17.getText());
        }
        if (board18.getText().length() > 0) {
            s.grid[0][7].value = parseInt(board18.getText());
        }
        if (board19.getText().length() > 0) {
            s.grid[0][8].value = parseInt(board19.getText());
        }
        if (board21.getText().length() > 0) {
            s.grid[1][0].value = parseInt(board21.getText());
        }
        if (board22.getText().length() > 0) {
            s.grid[1][1].value = parseInt(board22.getText());
        }
        if (board23.getText().length() > 0) {
            s.grid[1][2].value = parseInt(board23.getText());
        }
        if (board24.getText().length() > 0) {
            s.grid[1][3].value = parseInt(board24.getText());
        }
        if (board25.getText().length() > 0) {
            s.grid[1][4].value = parseInt(board25.getText());
        }
        if (board26.getText().length() > 0) {
            s.grid[1][5].value = parseInt(board26.getText());
        }
        if (board27.getText().length() > 0) {
            s.grid[1][6].value = parseInt(board27.getText());
        }
        if (board28.getText().length() > 0) {
            s.grid[1][7].value = parseInt(board28.getText());
        }
        if (board29.getText().length() > 0) {
            s.grid[1][8].value = parseInt(board29.getText());
        }
        if (board31.getText().length() > 0) {
            s.grid[2][0].value = parseInt(board31.getText());
        }
        if (board32.getText().length() > 0) {
            s.grid[2][1].value = parseInt(board32.getText());
        }
        if (board33.getText().length() > 0) {
            s.grid[2][2].value = parseInt(board33.getText());
        }
        if (board34.getText().length() > 0) {
            s.grid[2][3].value = parseInt(board34.getText());
        }
        if (board35.getText().length() > 0) {
            s.grid[2][4].value = parseInt(board35.getText());
        }
        if (board36.getText().length() > 0) {
            s.grid[2][5].value = parseInt(board36.getText());
        }
        if (board37.getText().length() > 0) {
            s.grid[2][6].value = parseInt(board37.getText());
        }
        if (board38.getText().length() > 0) {
            s.grid[2][7].value = parseInt(board38.getText());
        }
        if (board39.getText().length() > 0) {
            s.grid[2][8].value = parseInt(board39.getText());
        }
        if (board41.getText().length() > 0) {
            s.grid[3][0].value = parseInt(board41.getText());
        }
        if (board42.getText().length() > 0) {
            s.grid[3][1].value = parseInt(board42.getText());
        }
        if (board43.getText().length() > 0) {
            s.grid[3][2].value = parseInt(board43.getText());
        }
        if (board44.getText().length() > 0) {
            s.grid[3][3].value = parseInt(board44.getText());
        }
        if (board45.getText().length() > 0) {
            s.grid[3][4].value = parseInt(board45.getText());
        }
        if (board46.getText().length() > 0) {
            s.grid[3][5].value = parseInt(board46.getText());
        }
        if (board47.getText().length() > 0) {
            s.grid[3][6].value = parseInt(board47.getText());
        }
        if (board48.getText().length() > 0) {
            s.grid[3][7].value = parseInt(board48.getText());
        }
        if (board49.getText().length() > 0) {
            s.grid[3][8].value = parseInt(board49.getText());
        }
        if (board51.getText().length() > 0) {
            s.grid[4][0].value = parseInt(board51.getText());
        }
        if (board52.getText().length() > 0) {
            s.grid[4][1].value = parseInt(board52.getText());
        }
        if (board53.getText().length() > 0) {
            s.grid[4][2].value = parseInt(board53.getText());
        }
        if (board54.getText().length() > 0) {
            s.grid[4][3].value = parseInt(board54.getText());
        }
        if (board55.getText().length() > 0) {
            s.grid[4][4].value = parseInt(board55.getText());
        }
        if (board56.getText().length() > 0) {
            s.grid[4][5].value = parseInt(board56.getText());
        }
        if (board57.getText().length() > 0) {
            s.grid[4][6].value = parseInt(board57.getText());
        }
        if (board58.getText().length() > 0) {
            s.grid[4][7].value = parseInt(board58.getText());
        }
        if (board59.getText().length() > 0) {
            s.grid[4][8].value = parseInt(board59.getText());
        }
        if (board61.getText().length() > 0) {
            s.grid[5][0].value = parseInt(board61.getText());
        }
        if (board62.getText().length() > 0) {
            s.grid[5][1].value = parseInt(board62.getText());
        }
        if (board63.getText().length() > 0) {
            s.grid[5][2].value = parseInt(board63.getText());
        }
        if (board64.getText().length() > 0) {
            s.grid[5][3].value = parseInt(board64.getText());
        }
        if (board65.getText().length() > 0) {
            s.grid[5][4].value = parseInt(board65.getText());
        }
        if (board66.getText().length() > 0) {
            s.grid[5][5].value = parseInt(board66.getText());
        }
        if (board67.getText().length() > 0) {
            s.grid[5][6].value = parseInt(board67.getText());
        }
        if (board68.getText().length() > 0) {
            s.grid[5][7].value = parseInt(board68.getText());
        }
        if (board69.getText().length() > 0) {
            s.grid[5][8].value = parseInt(board69.getText());
        }
        if (board71.getText().length() > 0) {
            s.grid[6][0].value = parseInt(board71.getText());
        }
        if (board72.getText().length() > 0) {
            s.grid[6][1].value = parseInt(board72.getText());
        }
        if (board73.getText().length() > 0) {
            s.grid[6][2].value = parseInt(board73.getText());
        }
        if (board74.getText().length() > 0) {
            s.grid[6][3].value = parseInt(board74.getText());
        }
        if (board75.getText().length() > 0) {
            s.grid[6][4].value = parseInt(board75.getText());
        }
        if (board76.getText().length() > 0) {
            s.grid[6][5].value = parseInt(board76.getText());
        }
        if (board77.getText().length() > 0) {
            s.grid[6][6].value = parseInt(board77.getText());
        }
        if (board78.getText().length() > 0) {
            s.grid[6][7].value = parseInt(board78.getText());
        }
        if (board79.getText().length() > 0) {
            s.grid[6][8].value = parseInt(board79.getText());
        }
        if (board81.getText().length() > 0) {
            s.grid[7][0].value = parseInt(board81.getText());
        }
        if (board82.getText().length() > 0) {
            s.grid[7][1].value = parseInt(board82.getText());
        }
        if (board83.getText().length() > 0) {
            s.grid[7][2].value = parseInt(board83.getText());
        }
        if (board84.getText().length() > 0) {
            s.grid[7][3].value = parseInt(board84.getText());
        }
        if (board85.getText().length() > 0) {
            s.grid[7][4].value = parseInt(board85.getText());
        }
        if (board86.getText().length() > 0) {
            s.grid[7][5].value = parseInt(board86.getText());
        }
        if (board87.getText().length() > 0) {
            s.grid[7][6].value = parseInt(board87.getText());
        }
        if (board88.getText().length() > 0) {
            s.grid[7][7].value = parseInt(board88.getText());
        }
        if (board89.getText().length() > 0) {
            s.grid[7][8].value = parseInt(board89.getText());
        }
        if (board91.getText().length() > 0) {
            s.grid[8][0].value = parseInt(board91.getText());
        }
        if (board92.getText().length() > 0) {
            s.grid[8][1].value = parseInt(board92.getText());
        }
        if (board93.getText().length() > 0) {
            s.grid[8][2].value = parseInt(board93.getText());
        }
        if (board94.getText().length() > 0) {
            s.grid[8][3].value = parseInt(board94.getText());
        }
        if (board95.getText().length() > 0) {
            s.grid[8][4].value = parseInt(board95.getText());
        }
        if (board96.getText().length() > 0) {
            s.grid[8][5].value = parseInt(board96.getText());
        }
        if (board97.getText().length() > 0) {
            s.grid[8][6].value = parseInt(board97.getText());
        }
        if (board98.getText().length() > 0) {
            s.grid[8][7].value = parseInt(board98.getText());
        }
        if (board99.getText().length() > 0) {
            s.grid[8][8].value = parseInt(board99.getText());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BC3SGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BC3SGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BC3SGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BC3SGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BC3SGUI().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextPane HelpPanel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField board11;
    private javax.swing.JTextField board12;
    private javax.swing.JTextField board13;
    private javax.swing.JTextField board14;
    private javax.swing.JTextField board15;
    private javax.swing.JTextField board16;
    private javax.swing.JTextField board17;
    private javax.swing.JTextField board18;
    private javax.swing.JTextField board19;
    private javax.swing.JTextField board21;
    private javax.swing.JTextField board22;
    private javax.swing.JTextField board23;
    private javax.swing.JTextField board24;
    private javax.swing.JTextField board25;
    private javax.swing.JTextField board26;
    private javax.swing.JTextField board27;
    private javax.swing.JTextField board28;
    private javax.swing.JTextField board29;
    private javax.swing.JTextField board31;
    private javax.swing.JTextField board32;
    private javax.swing.JTextField board33;
    private javax.swing.JTextField board34;
    private javax.swing.JTextField board35;
    private javax.swing.JTextField board36;
    private javax.swing.JTextField board37;
    private javax.swing.JTextField board38;
    private javax.swing.JTextField board39;
    private javax.swing.JTextField board41;
    private javax.swing.JTextField board42;
    private javax.swing.JTextField board43;
    private javax.swing.JTextField board44;
    private javax.swing.JTextField board45;
    private javax.swing.JTextField board46;
    private javax.swing.JTextField board47;
    private javax.swing.JTextField board48;
    private javax.swing.JTextField board49;
    private javax.swing.JTextField board51;
    private javax.swing.JTextField board52;
    private javax.swing.JTextField board53;
    private javax.swing.JTextField board54;
    private javax.swing.JTextField board55;
    private javax.swing.JTextField board56;
    private javax.swing.JTextField board57;
    private javax.swing.JTextField board58;
    private javax.swing.JTextField board59;
    private javax.swing.JTextField board61;
    private javax.swing.JTextField board62;
    private javax.swing.JTextField board63;
    private javax.swing.JTextField board64;
    private javax.swing.JTextField board65;
    private javax.swing.JTextField board66;
    private javax.swing.JTextField board67;
    private javax.swing.JTextField board68;
    private javax.swing.JTextField board69;
    private javax.swing.JTextField board71;
    private javax.swing.JTextField board72;
    private javax.swing.JTextField board73;
    private javax.swing.JTextField board74;
    private javax.swing.JTextField board75;
    private javax.swing.JTextField board76;
    private javax.swing.JTextField board77;
    private javax.swing.JTextField board78;
    private javax.swing.JTextField board79;
    private javax.swing.JTextField board81;
    private javax.swing.JTextField board82;
    private javax.swing.JTextField board83;
    private javax.swing.JTextField board84;
    private javax.swing.JTextField board85;
    private javax.swing.JTextField board86;
    private javax.swing.JTextField board87;
    private javax.swing.JTextField board88;
    private javax.swing.JTextField board89;
    private javax.swing.JTextField board91;
    private javax.swing.JTextField board92;
    private javax.swing.JTextField board93;
    private javax.swing.JTextField board94;
    private javax.swing.JTextField board95;
    private javax.swing.JTextField board96;
    private javax.swing.JTextField board97;
    private javax.swing.JTextField board98;
    private javax.swing.JTextField board99;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField sudoTitle;
    // End of variables declaration//GEN-END:variables
}
